on:
  schedule:
    - cron: '0/5 * * * *'
  push:
    branches: master

name: Scrape

jobs:
  render:
    name: Scrape
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("rvest","dplyr","tidyverse"))'
      - name: Scrape
        run: Rscript action.R
      - name: Commit results
        run: |
          git config --local user.name "Automated action"
          git add -A
          git commit -m --local user.email "50101641+Macweese@users.noreply.github.com" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
